version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/cccm-backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/cccm-frontend"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
