version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/cccm-backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/cccm-frontend"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
