version: "3.3"

services:

  backend:
    container_name: cccm-api
    image: cccm-api
    build:
      context: ./cccm-backend
      args:
        - SERVICE_NAME=cccm-api
        - SKIP_TESTS=true
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}  
      - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
    networks:
      - cccm

  role-sync:
    container_name: cccm-role-sync
    image: cccm-role-sync
    build:
      context: ./cccm-backend/cccm-role-sync
      args:
        - SERVICE_NAME=cccm-role-sync
        - SKIP_TESTS=true
    ports:
      - "8090:8090"
    environment:
      - CCCM_API_BASE=${CCCM_API_BASE}
      - CCCM_KEYCLOAK_BASE=${CCCM_KEYCLOAK_BASE}
      - CCCM_KEYCLOAK_REALM=${CCCM_KEYCLOAK_REALM}
      - CCCM_KEYCLOAK_CLIENT=${CCCM_KEYCLOAK_CLIENT}
      - CCCM_KEYCLOAK_USERNAME=${CCCM_KEYCLOAK_USERNAME}
      - CCCM_KEYCLOAK_PASSWORD=${CCCM_KEYCLOAK_PASSWORD}
      - CCCM_KEYCLOAK_URL=${CCCM_KEYCLOAK_URL}
      - CCCM_KEYCLOAK_SECRET=${CCCM_KEYCLOAK_SECRET}
      - SPLUNK_ENABLED=${SPLUNK_ENABLED}
      - SPLUNK_URL=${SPLUNK_URL}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
    networks:
      - cccm

  frontend:
    container_name: cccm-web
    image: cccm-web
    build:
      context: ./cccm-frontend
    ports:
      - "8000:8000"
    networks:
      - cccm

  
networks:
  cccm:
    driver: bridge
