version: "3.7"
services:
  ##############################################################################################
  ####                                        KEYCLOAK Config                                ###
  ##############################################################################################
  keycloak-config:
    build:
      context: ./infrastructure/keycloak
      args:
        - KEYCLOAK_URL=http://keycloak:8080
