# Work In Progress
version: "3.3"

services:
  quarkas:
    container_name: cccm-api
    image: cccm-api
    build:
      context: .
      dockerfile: code-with-quarkus/src/main/docker/Dockerfile.native
    ports:
      - 8000:8000
  vue-project:
    container_name: cccm-web
    image: cccm-web
    build:
      context: vue-project
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"