openapi: 3.0.0
info:
  description: CCCM API
  title: Community Corrections Case Management API
  version: 0.0.1
servers:
  - url: http://localhost:8080
tags:
  - description: Endpoints for client data
    name: clients
  - description: Endpoints for form data
    name: forms
  - description: Endpoints for code tables data
    name: lookups
paths:
  /clients:
    get:
      operationId: SearchClients
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: soundex
          schema:
            type: boolean
        - in: query
          name: birthYear
          schema:
            type: integer
        - in: query
          name: age
          schema:
            type: integer
        - in: query
          name: address
          schema:
            type: string
        - in: query
          name: location
          schema:
            type: string
        - in: query
          name: gender
          schema:
            type: string
        - in: query
          name: clientId
          schema:
            type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientList'
          description: get all forms
      summary: search for clients
      tags:
        - clients
      x-accepts: application/json
      x-tags:
        - tag: clients
  /clients/{clientId}/photo:
    get:
      operationId: GetClientPhoto
      parameters:
        - explode: false
          in: path
          name: clientId
          required: true
          schema:
            type: number
          style: simple
      responses:
        "200":
          description: get client photo
          content:
            image/*:
              schema:
                type: string
                format: binary
      tags:
        - clients
  /clients/{clientId}:
    get:
      operationId: GetClient
      parameters:
        - explode: false
          in: path
          name: clientId
          required: true
          schema:
            type: number
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: get a client
      tags:
        - clients
  /forms:
    get:
      operationId: GetForms
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormList'
          description: get all forms
      summary: get all forms
      tags:
        - forms
      x-accepts: application/json
      x-tags:
        - tag: forms
    post:
      operationId: Add Form
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDetails'
          description: Form was added
      summary: Add
      tags:
        - forms
      x-contentType: application/json
      x-accepts: application/json
      x-tags:
        - tag: forms
    put:
      operationId: Update Form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormDetails'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDetails'
          description: Form was updated
      summary: Update
      tags:
        - forms
      x-contentType: application/json
      x-accepts: application/json
      x-tags:
        - tag: forms
  /forms/{formId}:
    delete:
      operationId: DeleteForm
      parameters:
        - explode: false
          in: path
          name: formId
          required: true
          schema:
            type: number
          style: simple
      responses:
        "200":
          description: form was deleted
      summary: delete form by id
      tags:
        - forms
      x-accepts: application/json
      x-tags:
        - tag: forms
    get:
      operationId: GetFormById
      parameters:
        - explode: false
          in: path
          name: formId
          required: true
          schema:
            type: number
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDetails'
          description: form found
        "404":
          description: form not found
      summary: get a form by id
      tags:
        - forms
      x-accepts: application/json
      x-tags:
        - tag: forms
  /forms/{formType}:
    get:
      operationId: GetFormByType
      parameters:
        - explode: false
          in: path
          name: formType
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDetails'
          description: form found
        "404":
          description: form not found
      summary: get a form by type
      tags:
        - forms
      x-accepts: application/json
      x-tags:
        - tag: forms
  /formtypes:
    get:
      operationId: GetFormTypes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormTypeList'
          description: get all Form Types
      summary: get all form types
      tags:
        - lookups
      x-accepts: application/json
      x-tags:
        - tag: lookups
  /locations:
    get:
      operationId: GetLocations
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationList'
          description: get all locations
      summary: get all locations
      tags:
        - lookups
      x-accepts: application/json
      x-tags:
        - tag: lookups
components:
  schemas:
    FormDetails:
      description: Client
      properties:
        formId:
          type: number
        formClientId:
          type: number
        createdBy:
          type: string
        createdDate:
          format: date
          type: string
        updateDate:
          format: date
          type: string
        completedDate:
          format: date
          type: string
        formType:
          type: string
        formTitle:
          type: string
        formStatus:
          type: string
        crnacmp_types:
          allOf:
            - $ref: '#/components/schemas/CRNAType'
            - type: object
        rightPanel:
          type: array
          items:
            $ref: '#/components/schemas/SideCard'
        saveBtnGroup:
          allOf:
            - $ref: '#/components/schemas/ButtonGroup'
            - type: object
        saveDraftBtnGroup:
          allOf:
            - $ref: '#/components/schemas/ButtonGroup'
            - type: object
        data:
          type: array
          items:
            $ref: '#/components/schemas/FormSections'
      type: object
    CRNAType:
      type: object
      properties:
        type:
          type: string
        data:
          type: object
          properties:
            values:
              type: array
              items:
                type: object
                properties:
                  value:
                    type: string
                  label:
                    type: string
    SideCard:
      type: object
      properties:
        type:
          type: string
        contentType:
          type: string
        panelTitle:
          type: string
        panelKey:
          type: string
        contentKey:
          type: string
        dataArray:
          type: array
          items:
            type: string
        dataMatrix:
          type: array
          items:
            type: array
            items:
              type: string
        dataString:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        csNumber:
          type: string
        gender:
          type: string
        dob:
          type: string
        location:
          type: string
        finalOrderExpDate:
          type: string
        button:
          allOf:
            - $ref: '#/components/schemas/Button'
            - type: object
    Button:
      type: object
      properties:
        type:
          type: string
        action:
          type: string
        key:
          type: string
        label:
          type: string
        theme:
          type: string
    ButtonGroup:
      type: object
      properties:
        type:
          type: string
        button:
          type: array
          items:
            $ref: '#/components/schemas/Button'
    FormSections:
      type: object
      properties:
        section:
          type: string
        sideCardPanelHiddenList:
          type: array
          items:
            type: string
        subNavOnOff:
          type: string
        subsections:
          type: array
          items:
            $ref: '#/components/schemas/FormSubSections'
    FormSubSections:
      type: object
      properties:
        type:
          type: string
        sectionKey:
          type: string
        subSectionKey:
          type: string
        sectionTitle:
          type: string
        sectionSubTitle:
          type: string
        questionLabel:
          type: string
        label:
          type: string
        label_textarea:
          type: string
        key:
          type: string
        defaultValue:
          type: string
        values:
          type: array
          items:
            $ref: "#/components/schemas/QuestionBody"
        comments:
          allOf:
            - $ref: '#/components/schemas/CommentsArea'
            - type: object
        interventionNeeded:
          allOf:
            - $ref: '#/components/schemas/InterventionArea'
            - type: object
        questionId:
          type: number
        questionAnswerClientId:
          type: number
        questionAnswer:
          type: string
    QuestionBody:
      properties:
        label:
          type: string
        value:
          type: string
        shortcut:
          type: string
    CommentsArea:
      type: object
      properties:
        type:
          type: string
        key:
          type: string

    InterventionArea:
      type: object
      properties:
        type:
          type: string
        key:
          type: string
        defaultValue:
          type: boolean
    FormList:
      example:
        items:
          - formId: 0.8008281904610115
            updateDate: 2000-01-23
            formType: formType
            createdDate: 2000-01-23
            createdBy: createdBy
            completedDate: 2000-01-23
          - formId: 0.8008281904610115
            updateDate: 2000-01-23
            formType: formType
            createdDate: 2000-01-23
            createdBy: createdBy
            completedDate: 2000-01-23
      properties:
        items:
          description: FormDetails
          items:
            $ref: '#/components/schemas/FormDetails'
          type: array
      type: object
    FormType:
      description: Form Type
      example:
        typeCd: typeCd
        typeId: 0.8008281904610115
        typeDescription: typeDescription
      properties:
        typeId:
          type: number
        typeCd:
          type: string
        typeDescription:
          type: string
      type: object
    FormTypeList:
      example:
        items:
          - typeCd: typeCd
            typeId: 0.8008281904610115
            typeDescription: typeDescription
          - typeCd: typeCd
            typeId: 0.8008281904610115
            typeDescription: typeDescription
      properties:
        items:
          description: FormType
          items:
            $ref: '#/components/schemas/FormType'
          type: array
      type: object
    Location:
      description: Location
      example:
        locationCd: locationCd
        locationId: 0.8008281904610115
        locationDescription: locationDescription
      properties:
        locationId:
          type: number
        locationCd:
          type: string
        locationDescription:
          type: string
      type: object
    LocationList:
      example:
        items:
          - locationCd: locationCd
            locationId: 0.8008281904610115
            locationDescription: locationDescription
          - locationCd: locationCd
            locationId: 0.8008281904610115
            locationeDescription: locationDescription
      properties:
        items:
          description: Location
          items:
            $ref: '#/components/schemas/Location'
          type: array
      type: object
    Component:
      type: object
      properties:
        key:
          type: string
        title:
          type: string
        collapsible:
          type: boolean
        label:
          type: string
        inline:
          type: boolean
        tableView:
          type: boolean
        content:
          type: string
        input:
          type: boolean
        type:
          type: string
        tag:
          type: string
        refreshOnChange:
          type: boolean
        disableOnInvalid:
          type: boolean
        components:
          type: array
          items:
            $ref: "#/components/schemas/Component"
        attrs:
          type: array
          items:
            $ref: '#/components/schemas/Attr'
    Attr:
      type: object
      properties:
        attr:
          type: string
        value:
          type: string
    ClientList:
      type: array
      items:
        $ref: '#/components/schemas/Client'
    Client:
      type: object
      properties:
        clientNum:
          type: string
        clientName:
          type: string
        firstName:
          type: string
        LastName:
          type: string
        gender:
          type: string
        clientAge:
          type: number
        birthDate:
          type: string
        address:
          type: array
          items:
            $ref: "#/components/schemas/Address"
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        postalCode:
          type: string
