export const APP_GLOBALS = {
  $CONST_FORMTYPE_CRNA: 'CRNA',
  $CONST_FORMTYPE_SARA: 'SARA',
  $CONST_FORMTYPE_ACUTE: 'ACUTE',
  $CONST_FORMTYPE_STAT99R: 'STAT99R',
  $CONST_FORMTYPE_STABLE: 'STABLE',
  $CONST_FORMTYPE_SO_OVERALL: 'SMO_OVERALL',
  $CONST_FORMTYPE_CMRP: 'CMRP',
  $CONST_FORMTYPE_RNA: 'ALL',
  $CONST_DATATABLE_ITEMS_PER_PAGE: 15,
  $CONST_DATATABLE_PAGE_FILTERLIST: [1, 2, 5, 10, 15, 20, 30, 50],
  $CONST_LABEL_SMO_OVERALL_BP_SECTION: 'Behavioral Progression and Self Management Plan',
  $CONST_SUBSECTIONTYPE_INTERVENTION: 'INTERVENTION',
  $CONST_SUBSECTIONTYPE_SUPERVISIONPLANCOMMENT: 'SUPERVISIONPLANCOMMENT',
  $CONST_SUBSECTIONTYPE_FORMCOMMENT: 'FORMCOMMENT',
  $CONST_SUBSECTIONTYPE_RESPONSIVITY: 'RESPONSIVITY',
  $USER_GROUP_PO: 'po',
  $USER_GROUP_SUPERVISOR: 'supervisor',
  $USER_GROUP_ADMIN: 'admin',
  $USER_GROUP_ITRP: 'itrp',
  $USER_GROUP_RESEARCHER: 'researcher',
  $USER_GROUP_ADMIN_COMM: 'admin-comm',
  $FORM_STATUS_INCOMPLETE: 'Incomplete',
  $FORM_STATUS_COMPLETE: 'Complete',
  $FORM_TYPE_INITIAL: 'Initial',
  $FORM_TYPE_REASSESSMENT: 'Reassessment',
  $ROUTER_NAME_HOME: 'home',
  $ROUTER_NAME_CMPFORM: 'cmpform',
  $ROUTER_NAME_DASHBOARDITRP: 'dashboarditrp',
  $ROUTER_NAME_DASHBOARDPO: 'dashboardpo',
  $ROUTER_NAME_DASHBOARDSUPERVISOR: 'dashboardsupervisor',
  $ROUTER_NAME_CLIENTRECORD: 'clientrecord',
  $ROUTER_NAME_CLIENTSEARCH: 'clientsearch',
  $ROUTER_NAME_PRINT: 'printView',
  $AUTH_ROLE_PO: 'auth-po',
  $AUTH_ROLE_SUPERVISOR: 'auth-supervisor',
  $AUTH_ROLE_ADMIN: 'auth-admin',
  $AUTH_ROLE_ITRP: 'auth-itrp',
  $AUTH_ROLE_RESEARCHER: 'auth-researcher',
  $AUTH_ROLE_ADMIN_COMM: 'auth-admin-comm',
  $AUTH_SHOW_TREND: 'show-trend',
  $ROLE_PO_MANAGE: 'po-manage',
  $KEY_SOURCES_CONTACTED: 'input_key_sourceContacted',
  $FORM_INFO: [
    { formType: 'CRNA', autoCalcOnFormload: false, autoCalcOnFormComplete: false, autoCalcOnFormClose: false, cmp: true, formTypeDesc: 'CRNA', dataRefreshSectionIndex: '', formTitle: 'Community Risk Needs Assessment Form (CRNA-CMP)', assessmentStatusRequired: true, formTypeLabel: 'CRNA-CMP Type', showSourcesContacted: true },
    { formType: 'SARA', autoCalcOnFormload: false, autoCalcOnFormComplete: false, autoCalcOnFormClose: false, cmp: false, formTypeDesc: 'SARA', dataRefreshSectionIndex: '', formTitle: 'SARA', assessmentStatusRequired: true, formTypeLabel: 'SARA Type', showSourcesContacted: false },
    { formType: 'ACUTE', autoCalcOnFormload: false, autoCalcOnFormComplete: false, autoCalcOnFormClose: false, cmp: false, formTypeDesc: 'Acute', dataRefreshSectionIndex: '1', formTitle: 'Acute', assessmentStatusRequired: true, formTypeLabel: 'Acute Type', showSourcesContacted: true },
    { formType: 'STABLE', autoCalcOnFormload: false, autoCalcOnFormComplete: false, autoCalcOnFormClose: false, cmp: true, formTypeDesc: 'Stable', dataRefreshSectionIndex: '5', formTitle: 'Stable', assessmentStatusRequired: true, formTypeLabel: 'Stable Type', showSourcesContacted: true },
    { formType: 'STAT99R', autoCalcOnFormload: false, autoCalcOnFormComplete: false, autoCalcOnFormClose: false, cmp: false, formTypeDesc: 'Static-99R', dataRefreshSectionIndex: '1', formTitle: 'Static-99R', assessmentStatusRequired: true, formTypeLabel: 'Static-99R Type', showSourcesContacted: true },
    { formType: 'SMO_OVERALL', autoCalcOnFormload: true, autoCalcOnFormComplete: true, autoCalcOnFormClose: true, cmp: false, formTypeDesc: 'SMO-Overall-CMP', dataRefreshSectionIndex: '', formTitle: 'SMO-Overall-CMP', assessmentStatusRequired: true, formTypeLabel: 'SMO-Overall-CMP Type', showSourcesContacted: true },
    { formType: 'CMRP', autoCalcOnFormload: true, autoCalcOnFormComplete: true, autoCalcOnFormClose: true, cmp: false, formTypeDesc: 'Custody-CMRP', dataRefreshSectionIndex: '', formTitle: 'Custody-CMRP', assessmentStatusRequired: true, formTypeLabel: 'Type', showSourcesContacted: true }
  ],
  $BUTTON_TEXT_SUBMIT: 'Submit Form',
  $BUTTON_TEXT_SAVE_CONTINUE: 'Save and Continue'
} as const;

export const installGlobals = (app: any) => {
  Object.assign(app.config.globalProperties, APP_GLOBALS);
};
