package ca.bc.gov.open.jag.api.error;

public enum CCCMErrorCode {
    RECORDNOTFOUND,
    DATALOADERROR,
    INVALIDUSER,
    VALIDATIONERROR,
    VALIDATIONERRORWITHRESULT,
    CLONEVALIDATIONERROR,
    INVALIDREQUEST,
    UNKNOWN
}
