#This workflow requires an input and based on that input pulls the appropriate image and tags it with the next environments name
#This workflow will also likely change as we get more of our environment set up

name: Promote the backend image to test or prod on Gold and GoldDR cluster

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
        - test
        - prod
jobs:
  run-test:
    runs-on: ubuntu-latest
    environment: 
      name: Testing
    if: ${{ github.event.inputs.environment == 'test' }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      - name: Pull Dev Image 
        run: |  
          docker pull artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:dev

      - name: Docker Tag Version Test
        run: |  
          docker tag artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:dev artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:test
          
      - name: Docker Push Version Test to Artifactory
        run: |  
          docker push artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:test
         
       # Get SHORT_SHA for the version
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"
      
      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_OPS_SSH_KEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "UCMP GitHub Actions"
          git clone -b test --single-branch git@github.com:bcgov-c/tenant-gitops-ed5723.git

          cd tenant-gitops-ed5723/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/apitag: .*/apitag: dev # Image Updated on $DATETIME/" ../deploy/test_values.yaml

          sed -i "s/apiversion: .*/apiversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml
          
          git add .
          
          git add ../deploy/test_values.yaml
          
          # Repackage Helm Chart      

          cd ucmp-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update TEST API image tag"
          git push origin test  # Update the branch name as needed

  run-prod:
    runs-on: ubuntu-latest
    environment: 
      name: Production
    if: ${{ github.event.inputs.environment == 'prod' }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
      - name: Pull Dev Image 
        run: |  
          docker pull artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod

      #- name: Docker Tag Prod Backup
      #  run: |
      #    docker pull artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod 
      #    docker tag artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod-backup
      #    docker push artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod-backup
          
      - name: Pull Test Image
        run: |  
          docker pull artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:test
      
      - name: Docker Tag Version Prod
        run: |  
          docker tag artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:test artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod
          
      - name: Docker Push Version Prod to Gold and GoldDR
        run: |  
          docker push artifacts.developer.gov.bc.ca/ced5-ucmp-api/ucmp-api:prod

       # Get SHORT_SHA for the version
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"
      
      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_OPS_SSH_KEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "UCMP GitHub Actions"
          git clone -b main --single-branch git@github.com:bcgov-c/tenant-gitops-ed5723.git

          cd tenant-gitops-ed5723/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/apitag: .*/apitag: dev # Image Updated on $DATETIME/" ../deploy/prod_values.yaml

          sed -i "s/apiversion: .*/apiversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/prod_values.yaml
          
          git add .
          
          git add ../deploy/prod_values.yaml
          
          # Repackage Helm Chart      

          cd ucmp-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Prod API image tag"
          git push origin main  # Update the branch name as needed

      