name: Generate/Upload Quarkus Coverage Report To Code Climate 

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  quarkus:
    env:
      CC_TEST_REPORTER_ID: 889fcd8abd72cd5fd355c136d4b143130731fb7052aa9442f57a30ce0d482701

    name: Build/Test Java Project
    runs-on: ubuntu-latest

    steps:

      # Checkout Project
      - name: Checkout CCCM Repository
        uses: actions/checkout@v4


      # Trimming the ref to main in order to publish correct report
      - name: Set ref/head/main to main
        run: |
          echo "GIT_BRANCH=main" >> $GITHUB_ENV
        if: env.GIT_BRANCH == 'refs/heads/main'

      # Setup Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
     
      # Run Maven Verify to generate all jacoco reports
      - name: Build with Maven
        run: mvn -B verify -P all -f cccm-backend/pom.xml
