name: Build & Push Role Sync Image to Gold and GoldDR cluster

on:
  push:
    branches: [main]
    paths:
      - 'cccm-backend/cccm-role-sync/**'
  workflow_dispatch:
env:
  IMAGE_NAME: ucmp-role-sync
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Docker Build Role Sync Image
        run: |            
          docker compose build role-sync
      
      - name: Docker Tag Version Dev
        run: |  
          docker tag role-sync artifacts.developer.gov.bc.ca/ced5-ucmp-role-sync/${{env.IMAGE_NAME}}:dev
          
      - name: Docker Push Version to Artifactory
        run: |  
          docker push artifacts.developer.gov.bc.ca/ced5-ucmp-role-sync/${{env.IMAGE_NAME}}:dev
      
      - name: Vulnerability Scan Backend
        uses: Azure/container-scan@v0
        continue-on-error: true
        with:
          image-name: artifacts.developer.gov.bc.ca/ced5-ucmp-role-sync/${{env.IMAGE_NAME}}:dev

       # Get SHORT_SHA for the version
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"
      
      - name: Set GitOps SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_OPS_SSH_KEY }}

      - name: Update Helm Values and Commit
        id: helm
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "UCMP GitHub Actions"
          git clone -b develop --single-branch git@github.com:bcgov-c/tenant-gitops-ed5723.git

          cd tenant-gitops-ed5723/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/rstag: .*/rstag: dev # Image Updated on $DATETIME/" ../deploy/dev_values.yaml

          sed -i "s/rsversion: .*/rsversion: ${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/dev_values.yaml
          
          git add .
          
          git add ../deploy/dev_values.yaml
          
          # Repackage Helm Chart      

          cd ucmp-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Dev role-sync image tag"
          git push origin develop  # Update the branch name as needed
      